
<?php
    $mediaBlock = $this->getLayout()->createBlock('Mage_Catalog_Block_Product_View_Media');
    
    
   
    $_product = $mediaBlock->getProduct();
    $_helper = $this->helper('Mage_Catalog_Helper_Output');
?>
<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
<p class="product-image product-image-zoom">
    <?php
        $_img = '<a href="'.$this->helper('Mage_Catalog_Helper_Image')->init($_product, 'image').'" rel="lightbox[kdecom]"> <img  id="image" src="'.$this->helper('Mage_Catalog_Helper_Image')->init($_product, 'image').'" alt="'.$this->__($mediaBlock->getImageLabel()).'" 
            title="'.$this->__($mediaBlock->getImageLabel()).'" /></a>';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>

<?php else: ?>
<p class="product-image">
    <?php
        $_img = '<img src="'.$mediaBlock->getBaseImageUrl($_product).'" alt="'.$this->__($mediaBlock->getImageLabel()).'" title="'.$this->__($mediaBlock->getImageLabel()).'" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
    ?>
</p>
<?php endif; ?>
<?php if (count($mediaBlock->getGalleryImages()) > 0): ?>
<div class="more-views">
    <h2><?php echo $this->__('More Views') ?></h2>
    <ul>
    <?php $_size = $mediaBlock->getBaseImageIconSize()?>
    <?php foreach ($mediaBlock->getGalleryImages() as $_image): ?>
        <li>
            <a href="<?php echo $this->helper('Mage_Catalog_Helper_Image')->init($mediaBlock->getProduct(), 'image', $_image->getFile()); ?>" rel="lightbox[kdecom]"
               title="<?php echo $this->__($_image->getLabel()) ?>">
                <img src="<?php echo $this->helper('Mage_Catalog_Helper_Image')->init($mediaBlock->getProduct(), 'image', $_image->getFile())->resize($_size); ?>" 
                     width="<?php echo $_size?>" height="<?php echo $_size?>" alt="<?php echo $this->__($_image->getLabel()) ?>"/>
            </a>
        </li>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
<?php
var_dump($this->getUrl());

?>
<script>
    imagePath = 'http://www.localhost.com/';
</script>